/**
 * GENERATED by scripts/film/tickets.mjs — do not edit.
 *
 * Every Done ticket whose number appears in a commit subject in v0.1.2..v0.2.0
 * (175 tickets), titled only with text commit history already published
 * (see the script for the order of sources).
 */
export const RELEASE_RANGE = "v0.1.2..v0.2.0";

export const RELEASE_TICKETS: readonly { number: number; title: string }[] = [
  {
    "number": 110,
    "title": "Add support for browser tooling inside Volli"
  },
  {
    "number": 166,
    "title": "Bound the workspace dependency walk at the project root (VC-160 item 2)"
  },
  {
    "number": 202,
    "title": "Integrate Split View for Tabs inside Volli"
  },
  {
    "number": 127,
    "title": "Automations: the Automations page"
  },
  {
    "number": 128,
    "title": "Automations: column Trigger and arming"
  },
  {
    "number": 203,
    "title": "Clean up design for the token usage/cost section in right sidebar"
  },
  {
    "number": 205,
    "title": "CMD+K improvements in Volli"
  },
  {
    "number": 131,
    "title": "Automations: provenance marks for Run-started Sessions"
  },
  {
    "number": 129,
    "title": "Automations: ticket rail and Run once"
  },
  {
    "number": 130,
    "title": "Automations: schedule Triggers and the scheduler"
  },
  {
    "number": 211,
    "title": "Land #418's 20 real updates, and stop the group tripping on the catalog"
  },
  {
    "number": 212,
    "title": "Absorb vite-plus 0.3.0 — the deferred toolchain bump, in lockstep"
  },
  {
    "number": 213,
    "title": "Retire the Node-ABI cache, because better-sqlite3 13 ships one binary for both runtimes"
  },
  {
    "number": 132,
    "title": "Automations: Offered list, Option-drag picker, and the lane view"
  },
  {
    "number": 133,
    "title": "Automations: notify when an unattended Run needs a person"
  },
  {
    "number": 220,
    "title": "P0: a Run opens its Session but never fires the kickoff prompt"
  },
  {
    "number": 221,
    "title": "P0: board crashes after ⌥-drag (constant on owner's display)"
  },
  {
    "number": 222,
    "title": "Automations design pass: composer declutter, schedule controls, page layout to owner's bar"
  },
  {
    "number": 233,
    "title": "Expose full timezone on trigger"
  },
  {
    "number": 229,
    "title": "Armed-but-off says one thing on every surface"
  },
  {
    "number": 223,
    "title": "Rebase restarted schedules"
  },
  {
    "number": 227,
    "title": "Surface kickoff delivery failures"
  },
  {
    "number": 230,
    "title": "Codify agent schedule retargeting"
  },
  {
    "number": 232,
    "title": "Remove drift-prone residue"
  },
  {
    "number": 224,
    "title": "Persist schedule lifecycle baseline"
  },
  {
    "number": 225,
    "title": "Preserve Project Run provenance across mint crashes"
  },
  {
    "number": 235,
    "title": "Restore row type scale"
  },
  {
    "number": 226,
    "title": "Durable main-side armed countdown (migration renumbered 037 after VC-225's 036)"
  },
  {
    "number": 236,
    "title": "Project live cards from runtime bindings"
  },
  {
    "number": 228,
    "title": "Armed expiry retains its command id for retry"
  },
  {
    "number": 231,
    "title": "Success toasts prefer main's launch-resolved name"
  },
  {
    "number": 234,
    "title": "Universal run landing — every door toasts, none navigate"
  },
  {
    "number": 241,
    "title": "The visual live state retires — rings say working/waiting"
  },
  {
    "number": 135,
    "title": "Model catalog: refresh provider model lists without a Pi bump"
  },
  {
    "number": 184,
    "title": "Enable multi-select for ticket cards"
  },
  {
    "number": 204,
    "title": "Restore budget-cause coverage"
  },
  {
    "number": 248,
    "title": "Activity Island closed-state feel playground in the Lab"
  },
  {
    "number": 251,
    "title": "Overlays make browser windows inactive"
  },
  {
    "number": 252,
    "title": "Browser tools timeout when workspace switch occurs"
  },
  {
    "number": 244,
    "title": "Make model refresh expose newly available provider models"
  },
  {
    "number": 250,
    "title": "Lab theming parity: mount the real canvas editor in the Lab shell"
  },
  {
    "number": 242,
    "title": "Keep the messages array append-only under preserved thinking"
  },
  {
    "number": 255,
    "title": "Model catalog: read Pi's pi.dev provider feed so GPT-6 Astra (and the next model) arrive without a Pi bump"
  },
  {
    "number": 249,
    "title": "The cards become control surfaces — row verbs, action reveal, arming, pin"
  },
  {
    "number": 256,
    "title": "A tooltip is a label, not a surface — pointer-transparent, no hover grace"
  },
  {
    "number": 254,
    "title": "Bump Pi to 0.85.0: signed-thinking recovery, Fable 5.1, and the VC-242 re-verification"
  },
  {
    "number": 257,
    "title": "Fix weird UI layout for automations"
  },
  {
    "number": 261,
    "title": "Fix image caret issues in ticket composer"
  },
  {
    "number": 259,
    "title": "Default Model Picker Improvements"
  },
  {
    "number": 9,
    "title": "Subagents: delegate tool + durable child Sessions"
  },
  {
    "number": 245,
    "title": "Measure Pi parallel execution and the Code Mode case"
  },
  {
    "number": 246,
    "title": "Build an agent activity bar inside the chat pane"
  },
  {
    "number": 263,
    "title": "Show provider usage limits (session/weekly windows, resets) on Model Access"
  },
  {
    "number": 239,
    "title": "Browser Tab ownership and animated Session cursor"
  },
  {
    "number": 260,
    "title": "Auto-titling should work on automation-triggered sessions"
  },
  {
    "number": 265,
    "title": "Fix long form question surfaces inside the User Question component"
  },
  {
    "number": 219,
    "title": "Smokes must stop hijacking the real pointer: synthetic input for packed-app e2e"
  },
  {
    "number": 125,
    "title": "Syntax-highlighting coverage: fill the notable grammar gaps"
  },
  {
    "number": 238,
    "title": "Headless agent Browser Tabs with in-chat live preview"
  },
  {
    "number": 262,
    "title": "Rename the Project Session Role to Board Session"
  },
  {
    "number": 270,
    "title": "Background shell sessions: run long commands off-turn, read them back, show them in the Activity Island"
  },
  {
    "number": 6,
    "title": "Plan/todo tool for structured sessions"
  },
  {
    "number": 268,
    "title": "Activity Island · mount in the chat plane and feed it Browser Tabs"
  },
  {
    "number": 269,
    "title": "Activity Island · subagent feed: working chips, peek overlay, promote to tab, stop"
  },
  {
    "number": 273,
    "title": "Images should render in-line in chat view"
  },
  {
    "number": 279,
    "title": "Subagents are never rows in a Session listing"
  },
  {
    "number": 285,
    "title": "Say the effective outcome at the control and on the Session"
  },
  {
    "number": 288,
    "title": "Wrap the interaction footers, and fall back to an inline diff by pane width"
  },
  {
    "number": 290,
    "title": "A closed terminal opens its own saved record, never a neighbouring tab"
  },
  {
    "number": 307,
    "title": "Judge markdown Preview's raw HTML on the file's own bytes"
  },
  {
    "number": 283,
    "title": "Teach Settings search the export's new name"
  },
  {
    "number": 287,
    "title": "Put the discovery reducer in the coverage gate, and test the st"
  },
  {
    "number": 286,
    "title": "Settle the mount-time venue read so no test leaves a rea"
  },
  {
    "number": 289,
    "title": "Withdrawal reports its landing, and the verdict card withdraws throug"
  },
  {
    "number": 327,
    "title": "Gzip and repack transcript artifacts"
  },
  {
    "number": 326,
    "title": "Compact native event ids"
  },
  {
    "number": 325,
    "title": "Prune migration backups after success"
  },
  {
    "number": 324,
    "title": "An `interrupted` listing state, CLI and app together item 2)"
  },
  {
    "number": 328,
    "title": "Add migration compaction operation"
  },
  {
    "number": 299,
    "title": "Quick Open ranks an exact basename above the artifact bonus"
  },
  {
    "number": 295,
    "title": "Notification preferences: wire the write path, honor it in every category, deep-link native alerts, keep a durable attention inbox"
  },
  {
    "number": 284,
    "title": "Storage Rescan separates read-only inspection from orphan cleanup"
  },
  {
    "number": 271,
    "title": "Usage limits: wire remaining subscription providers (Copilot, Kimi Code, xAI) onto the VC-263 reader seam"
  },
  {
    "number": 278,
    "title": "Park headless tabs in an off-screen stage so they can be captured and clicked"
  },
  {
    "number": 332,
    "title": "Bound the context window without weakening execution"
  },
  {
    "number": 304,
    "title": "Remove inert project harness default"
  },
  {
    "number": 311,
    "title": "Change Set rows read whole to VoiceOver and stay distinguishable at rail width"
  },
  {
    "number": 333,
    "title": "Split view: Remove the nested tab look and split the main tab bar instead"
  },
  {
    "number": 291,
    "title": "Investigate terminal reflow line loss and accessibility before 0.2.0 (feeds VC-107 acceptance)"
  },
  {
    "number": 310,
    "title": "Labels: case-insensitive identity and a merge tool (project has both 'UI' and 'ui')"
  },
  {
    "number": 337,
    "title": "Change Set watch: filter by git-ignore rules, share one watcher per worktree, pause background tabs"
  },
  {
    "number": 336,
    "title": "Execute kills its detached process group after a successful close, refuses daemonising forms"
  },
  {
    "number": 339,
    "title": "Concurrency budget in the Session env (vitest, cargo, make, go, pytest…) + vitest maxWorkers default"
  },
  {
    "number": 341,
    "title": "Orphan process sweep: spawn ledger + cwd sweep, reap processes no live Session owns (any language)"
  },
  {
    "number": 330,
    "title": "Draw host notices as transcript host rows, not user-style bubbles"
  },
  {
    "number": 340,
    "title": "Worktree retention: trim git-ignored artifacts from finished worktrees (any language), keep config"
  },
  {
    "number": 331,
    "title": "Compaction improvements: Autocompaction failures, tokenizer improvements + more"
  },
  {
    "number": 349,
    "title": "OpenCode Go 400s: send x-opencode-session on every Go request"
  },
  {
    "number": 338,
    "title": "Window the chat transcript so a long Session mounts a tail, not its history"
  },
  {
    "number": 243,
    "title": "Complete Browser Tab page-driven navigation on Electron 44"
  },
  {
    "number": 350,
    "title": "Restore the usage-limits popover beside ⌘K (dropped as out-of-scope from VC-271)"
  },
  {
    "number": 293,
    "title": "About: no 'Everything's working' while checks load; failure-specific fault titles; build/OS/schema in support report"
  },
  {
    "number": 351,
    "title": "Stress test browser tooling and fix any found issues"
  },
  {
    "number": 329,
    "title": "Automation improvements: make arming more obvious, on-off ergonomics + more"
  },
  {
    "number": 335,
    "title": "Improve prompt composer design and layout"
  },
  {
    "number": 352,
    "title": "Fix clipping at the top of the usage limits UI component"
  },
  {
    "number": 360,
    "title": "Architecture review: propose simplifications that remove cost rather than reduce it"
  },
  {
    "number": 353,
    "title": "Perf harness: repeatable benchmark matrix and baseline at real scale (1,200 sessions / 260k events)"
  },
  {
    "number": 354,
    "title": "Perf: React + Zustand store subscription and re-render audit at scale"
  },
  {
    "number": 359,
    "title": "UI interactions jank under concurrent session load (sidebar open/close)"
  },
  {
    "number": 217,
    "title": "Docs + website update for the 0.2.0 feature release"
  },
  {
    "number": 357,
    "title": "Chat panes chug when streaming text and scrolling at the same time"
  },
  {
    "number": 358,
    "title": "+ Chat should not create a durable Session until the first message is sent"
  },
  {
    "number": 363,
    "title": "Browser Tabs: benchmark and fix resize lag under sidebar transitions, plus agent-browser research pass"
  },
  {
    "number": 8,
    "title": "MCP client in the agent adapter"
  },
  {
    "number": 367,
    "title": "Crash recovery: Sessions cannot be resumed after a crash, and the composer silently queues into the void"
  },
  {
    "number": 355,
    "title": "Perf: RPC round-trip cost, SQLite at 260k events, and projection checkpoints"
  },
  {
    "number": 356,
    "title": "Perf: profile and reduce agent-runtime per-turn and per-tool-call cost"
  },
  {
    "number": 369,
    "title": "Take the rail's worktree status/diff reads off the Electron main thread"
  },
  {
    "number": 370,
    "title": "Send x-opencode-session on compaction summary requests"
  },
  {
    "number": 374,
    "title": "Sidebar: tickets.statusEntries re-runs a project-wide windowed query on every pane/tab open or close — key it on ticket status, not liveSignature"
  },
  {
    "number": 372,
    "title": "Rail worktree reads: serve the last status/change-set snapshot across Now↔Diffs flips and diff-tab opens (10 git children per flip today)"
  },
  {
    "number": 371,
    "title": "Model Access: cache the non-refresh inspect() snapshot — every chat plane / rail / composer mount re-runs ~40 provider probes and ~80 auth.json reads"
  },
  {
    "number": 373,
    "title": "Ticket open fan-out: 14+ IPC reads per switch, several duplicated — dedupe listForTicket, push-feed the rail roster, cache activity/TTL/usage across tab and rail flips"
  },
  {
    "number": 375,
    "title": "A discarded draft does not come back from the dead"
  },
  {
    "number": 383,
    "title": "Performance: Integrate better loading states using optimistic reads, UI and skeletons"
  },
  {
    "number": 381,
    "title": "Fix button and click interactions throughout the UI"
  },
  {
    "number": 382,
    "title": "Ticket Composer: Collapse the model and effort picker + fix attachments"
  },
  {
    "number": 386,
    "title": "Fix OpenCode Go auto-title utility requests"
  },
  {
    "number": 384,
    "title": "Fix activity bar popover width"
  },
  {
    "number": 376,
    "title": "Redesign the usage limits icon from Apple iPhone Duo inspiration"
  },
  {
    "number": 387,
    "title": "Performance: data.bootstrap re-reads the whole board on every data-changed"
  },
  {
    "number": 380,
    "title": "Agent-facing MCP management verbs, with provenance and a durable trail"
  },
  {
    "number": 389,
    "title": "Worktree: the async git runner has no aggregate bound"
  },
  {
    "number": 388,
    "title": "Performance: listSessions folds a project's whole roster in one main-thread transaction"
  },
  {
    "number": 368,
    "title": "context.reasoning_dropped never reaches the renderer: scrub removes a key its decode requires"
  },
  {
    "number": 385,
    "title": "Cut ticket workspace switching"
  },
  {
    "number": 397,
    "title": "Stop the MCP catalog overflowing its section, and its detail the page"
  },
  {
    "number": 396,
    "title": "Bump Pi to 0.85.1 and drop the identity patch"
  },
  {
    "number": 107,
    "title": "(2/2): xterm.js DOM engine behind TerminalEngine; retire restty and the GPU machinery"
  },
  {
    "number": 272,
    "title": "Drop tsconfig baseUrl for TS 7 and validate the solution file in typecheck"
  },
  {
    "number": 393,
    "title": "Freeze cached listing projections so callers cannot alias the fold cache"
  },
  {
    "number": 378,
    "title": "Hide the Plugins page until Agent Plugins support exists"
  },
  {
    "number": 403,
    "title": "Cache the concurrency-budget fleet count and make the CLI door's roster fold lazy"
  },
  {
    "number": 402,
    "title": "Sidebar: agent-kind glyph on terminal-companion rows"
  },
  {
    "number": 141,
    "title": "Tell the person when /compact found nothing to summarize"
  },
  {
    "number": 405,
    "title": "Move the ticket draft indicator next to the title bar"
  },
  {
    "number": 406,
    "title": "Reorganize and redesign the in-ticket right sidebar Now page"
  },
  {
    "number": 316,
    "title": "Profile and bound board/sidebar rendering at 300 / 3,000 / 10,000 tickets (columns render every card)"
  },
  {
    "number": 408,
    "title": "Release compliance: ship OFL font notices with docs and website"
  },
  {
    "number": 407,
    "title": "Release compliance: generate and ship complete desktop license notices"
  },
  {
    "number": 410,
    "title": "Provenance remediation: document and attribute vendored code and themes"
  },
  {
    "number": 409,
    "title": "License remediation: resolve LGPL and restricted dependency risks"
  },
  {
    "number": 411,
    "title": "License metadata: declare Apache-2.0 across workspace manifests"
  },
  {
    "number": 392,
    "title": "volli:session-list still blocks main after the chunked fold: readSessionProvenance runs up to 3 sync queries per Session"
  },
  {
    "number": 414,
    "title": "Apply owner identity to the Apache-2.0 license notice"
  },
  {
    "number": 412,
    "title": "Remove APCA-W3 and colorparsley from commercial OSS test paths"
  },
  {
    "number": 413,
    "title": "Remove vendored Ghostty theme catalog and risky third-party palettes"
  },
  {
    "number": 344,
    "title": "Terminal output is invisible to VoiceOver, and Tab cannot leave the terminal pane"
  },
  {
    "number": 418,
    "title": "AA primary labels and focus contrast"
  },
  {
    "number": 419,
    "title": "Keyboard ticket navigation loses focus and list context on Enter/Escape"
  },
  {
    "number": 416,
    "title": "Show model + effort concisely for subagents"
  },
  {
    "number": 421,
    "title": "Upgrade Pi runtime to 0.87.1 and migrate transcript context"
  },
  {
    "number": 420,
    "title": "Restate Pi's session-directory rule in the sidecar-migration fixture"
  },
  {
    "number": 300,
    "title": "Keep rail snippet hit visible when context clips"
  },
  {
    "number": 422,
    "title": "Exit cleanly on broken output pipes"
  },
  {
    "number": 297,
    "title": "Let main answer one Automation's history, and make Project activity reachable"
  },
  {
    "number": 428,
    "title": "Board chats on Anthropic models: 400 'You're out of extra usage' — trigger isolates to the mcp_* verb tools"
  },
  {
    "number": 429,
    "title": "Remove the \"Finished its task; its answer is in its own Session.\" string"
  },
  {
    "number": 440,
    "title": "Fix the options tab for branch picking in the ticket composer"
  },
  {
    "number": 446,
    "title": "Freeze the gesture's store reads against Automation roster writes"
  },
  {
    "number": 430,
    "title": "Relink a project after its folder is renamed or moved"
  },
  {
    "number": 431,
    "title": "Subagent Sessions anchor to their parent's model, never the Utility rung"
  },
  {
    "number": 449,
    "title": "Assert the churn the freeze removes, and drop the probe"
  },
  {
    "number": 443,
    "title": "Where time-to-merge goes, and the Volli-side fixes it found"
  }
];
