/**
 * The involuntary Session channels: what a harness reports about itself,
 * rather than what an agent chose to say.
 *
 * All three are addressed by `VOLLI_SESSION` alone and all three want terminal
 * FACTS on top of identity, so each resolves its own terminal record — which
 * is exactly why the table declares that none of them takes the dispatch's
 * projection snapshot or its identity lookup. `hook` arrives on a
 * process-per-event hot path, one process per event, and that laziness is
 * load-bearing there.
 *
 * Two of the three write the opaque terminal native detail, and they race:
 * hooks and wrapper announces arrive on separate socket connections, so the
 * read-modify-write is serialized per durable Session by the locks the context
 * carries.
 */

import { randomUUID } from "node:crypto";

import type Database from "better-sqlite3";
import {
  declaresInputNeeded as adapterDeclaresInputNeeded,
  displayTicketId,
  effectiveHarnessId,
  getHarnessAdapter,
  HARNESS_EVENTS,
  harnessEventOrder,
  harnessLabel,
  isFirstClassHarnessId,
  isHarnessEvent,
  parseHarnessId,
  shortSessionId,
  supersededHarnessEvent,
} from "@volli/shared";
import type { AgentRequest, AgentResponse, HarnessId, SessionRecord } from "@volli/shared";
import type { SessionEngine } from "@volli/session-engine";

import { getRegisteredHarness } from "../db/harness-registry-repo";
import { recordHarnessChannelEvent, recordHarnessLaunch } from "../db/harness-channel-repo";
import { getTicket } from "../db/tickets-repo";
import { recordHarnessDelivery } from "../harness-registry";
import {
  latestTerminalAttachment,
  readTerminalAttachmentDetail,
  terminalNativeReference,
  terminalSessionRecord,
} from "../session-control";
import { failure } from "./context";
import type { AgentCommandContext } from "./context";
import { dryRunResponse } from "./preview";

/**
 * The harness session id an event carries, trimmed — `null` when the event
 * carries none (most events don't), `undefined` when the field is present but
 * unusable, which is a malformed request rather than an absent id.
 */
function trimmedHarnessSessionId(value: unknown): string | null | undefined {
  if (value === undefined || value === null) return null;
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  if (trimmed.length === 0) return null;
  return trimmed.length <= 200 ? trimmed : undefined;
}

/**
 * Which harness fired this hook. `volli hook <harness> <event>` names it — the
 * slug is baked into the argv by the wrapper that wrote the harness's own hook
 * config — and it is not always the harness the session was launched with: a
 * user who types `codex` inside a claude-code session's terminal reaches the
 * codex wrapper, and codex's hooks then report from that same `VOLLI_SESSION`.
 * Read from the session row instead, every one of those events would be
 * recorded and announced as Claude Code's.
 *
 * The fallback, for the older hook contract that names no harness, is the
 * EFFECTIVE one — what last announced itself, not what the session launched
 * with — for exactly the same reason.
 *
 * Validated against the harnesses Volli knows — the first-class ids, the
 * registry rows, and the session's own — rather than accepted as a string.
 * Anything else is refused: the value is generated by Volli's own launch
 * machinery, so a name from outside that vocabulary is not a harness reporting,
 * it is something else talking, and it may not write to the capability ledger
 * under a name of its choosing. An absent argument is not an error — it is the
 * older hook contract, where the session is all there was to go on.
 */
function firingHarnessId(
  db: Database.Database,
  session: Pick<SessionRecord, "harnessId" | "activeHarnessId">,
  value: unknown,
): { ok: true; harnessId: HarnessId } | { ok: false; response: AgentResponse } {
  if (value === undefined || value === null) {
    return { ok: true, harnessId: effectiveHarnessId(session) };
  }
  const parsed = typeof value === "string" ? parseHarnessId(value) : null;
  if (parsed === null) {
    return {
      ok: false,
      response: failure("INVALID_REQUEST", `Invalid harness ${JSON.stringify(value)}.`),
    };
  }
  // Either of the session's OWN harnesses vouches for the name — the one it
  // launched with and the one now running. Both, not just the effective one: a
  // manifest untrusted since launch is no longer in the registry, and the
  // harness it started is still entitled to report on the session it is in.
  const known =
    parsed === session.harnessId ||
    parsed === effectiveHarnessId(session) ||
    isFirstClassHarnessId(parsed) ||
    getRegisteredHarness(db, parsed) !== undefined;
  return known
    ? { ok: true, harnessId: parsed }
    : {
        ok: false,
        response: failure("INVALID_REQUEST", `Unknown harness ${JSON.stringify(value)}.`),
      };
}

/**
 * Whether this harness's adapter declares `input.needed` at all.
 *
 * The renderer already refuses to raise a `waiting` state for one that doesn't
 * ({@link receiveHarnessEvent} in `@volli/shared`) — cursor maps both blocking
 * signals to null in its own source, so an `input.needed` bearing its name came
 * from something in the pipe rather than from cursor. Main has to apply the
 * same gate or it fires a native "needs you" interrupt against a sidebar
 * showing plain Idle, which is the disagreement the whole channel is built to
 * avoid. The delivery status alone cannot carry this: it is `verified` for
 * every first-class harness by construction, capability unread.
 *
 * A harness with no adapter here is a registered manifest, and main's own
 * registry is what vouches for it — matching the renderer, which believes an
 * id it cannot look up for exactly the same reason: the delivery is all the
 * evidence there is, and disbelieving it would hide a harness that IS
 * reporting.
 *
 * The rule itself is `@volli/shared`'s, deliberately: this gate and the
 * renderer's `waiting` fold have to agree, and the way two processes agree on a
 * predicate is by calling the same one. All this adds is main's lookup.
 */
function declaresInputNeeded(harnessId: HarnessId): boolean {
  return adapterDeclaresInputNeeded(getHarnessAdapter(harnessId));
}

async function updateTerminalNative(
  locks: Map<string, Promise<void>>,
  sessionEngine: SessionEngine,
  session: SessionRecord,
  update: (
    detail: NonNullable<ReturnType<typeof readTerminalAttachmentDetail>>,
  ) => ReturnType<typeof readTerminalAttachmentDetail>,
  occurredAt: number,
): Promise<SessionRecord | null> {
  // `attachment.native_referenced` replaces the opaque native detail rather
  // than patching it. Hooks and wrapper announces use separate socket
  // connections, so their read → observe pairs can overlap and otherwise drop
  // each other's field. Serialize that tiny read-modify-write critical section
  // per durable Session; different Sessions still proceed independently.
  const previous = locks.get(session.id) ?? Promise.resolve();
  let release: (() => void) | undefined;
  const current = new Promise<void>((resolve) => {
    release = resolve;
  });
  locks.set(session.id, current);
  await previous;
  try {
    const projection = await sessionEngine.getSession({ sessionId: session.id });
    if (projection === null) return null;
    const attachment = latestTerminalAttachment(projection.attachments);
    if (attachment === null || attachment.status !== "open") return null;
    const detail = readTerminalAttachmentDetail(attachment.native);
    if (detail === null) return null;
    const next = update(detail);
    if (next === null) return null;
    if (next === detail) return terminalSessionRecord(projection);
    await sessionEngine.observe({
      id: randomUUID(),
      kind: "attachment.native_referenced",
      sessionId: session.id,
      attachmentId: attachment.id,
      occurredAt,
      provenance: {
        source: { kind: "adapter", id: "terminal", detail: null },
        venue: { id: "local", kind: "local" },
      },
      native: terminalNativeReference(next),
    });
    const updated = await sessionEngine.getSession({ sessionId: session.id });
    return updated === null ? null : terminalSessionRecord(updated);
  } finally {
    release?.();
    if (locks.get(session.id) === current) locks.delete(session.id);
  }
}

/**
 * How many sessions main keeps an ordering watermark for. `VOLLI_SESSION`
 * outlives its PTY, so nothing here ever gets a reliable "this session is
 * finished" signal to delete on, and an unbounded map on the involuntary
 * channel's hot path is a leak with a long fuse. The cap is an order of
 * magnitude past any real number of concurrently firing sessions, and the entry
 * it evicts is the least recently heard from.
 */
const HARNESS_WATERMARK_LIMIT = 512;

/**
 * Records that a session has now been heard from at `firedAt`, evicting the
 * stalest watermark once the map is full. The delete-then-set is what moves the
 * entry to the young end — `Map` iterates in insertion order, which is the
 * whole LRU this needs and the only reason it costs nothing.
 */
function rememberFiredAt(
  watermarks: Map<string, number>,
  sessionId: string,
  firedAt: number,
): void {
  watermarks.delete(sessionId);
  watermarks.set(sessionId, firedAt);
  if (watermarks.size > HARNESS_WATERMARK_LIMIT) {
    const stalest = watermarks.keys().next();
    if (!stalest.done) watermarks.delete(stalest.value);
  }
}

/** `volli session link` — the harness's own resume id for this Volli session. */
export async function sessionLinkVerb(
  context: AgentCommandContext,
  request: AgentRequest,
): Promise<AgentResponse> {
  const { sessionEngine, terminalUpdateLocks, now } = context;
  // The harness reports its OWN resume/session UUID for the current Volli
  // session (interrupt/resume seed, issue #78/CONCEPT #21) — driven off
  // VOLLI_SESSION exactly like session.done, and typically wired to the
  // harness's session-start hook rather than run by hand.
  const sessionId = request.ctx.env.session;
  if (!sessionId) {
    return failure("CONTEXT_REQUIRED", "session link requires VOLLI_SESSION context.");
  }
  const projection = await sessionEngine.getSession({ sessionId });
  const session = projection === null ? null : terminalSessionRecord(projection);
  if (!session) return failure("SESSION_NOT_FOUND", `No session matches ${sessionId}.`);
  const idValue = request.args["id"];
  if (typeof idValue !== "string") {
    return failure("INVALID_REQUEST", "session link requires a harness session id.");
  }
  const harnessSessionId = idValue.trim();
  if (harnessSessionId.length === 0) {
    return failure("INVALID_REQUEST", "The harness session id must not be empty.");
  }
  if (harnessSessionId.length > 200) {
    return failure("INVALID_REQUEST", "The harness session id is too long (max 200 chars).");
  }
  const preview = dryRunResponse(request, {
    kind: "session",
    id: shortSessionId(session.id),
    label: `Session ${shortSessionId(session.id)}`,
  });
  if (preview !== null) return preview;
  const updated = await updateTerminalNative(
    terminalUpdateLocks,
    sessionEngine,
    session,
    (detail) => ({ ...detail, harnessSessionId }),
    now(),
  );
  if (updated === null)
    return failure("SESSION_ENDED", `Session ${shortSessionId(session.id)} has ended.`);
  return {
    v: 1,
    ok: true,
    data: { session: shortSessionId(session.id), harnessSessionId },
  };
}

/** `volli session harness` — which harness is now running in this session. */
export async function sessionHarnessVerb(
  context: AgentCommandContext,
  request: AgentRequest,
): Promise<AgentResponse> {
  const { options, sessionEngine, terminalUpdateLocks, now } = context;
  // The second involuntary channel: a harness's own PATH-shim wrapper,
  // one step before it execs, saying what is about to run and — when that
  // harness takes its session id on argv — asking for one. Addressed by
  // `VOLLI_SESSION` exactly as `session.link` and `hook` are.
  //
  // Why this exists at all: `sessions.harness_id` is written once at
  // INSERT and is the LAUNCH, which is a true and durable fact. But a
  // terminal outlives the agent that opened it — quit opencode, run
  // claude in the same pane — and everything that decides something about
  // the RUNNING agent (the resume command line, the needs-you
  // notification, the sidebar's label) was reading the launch. So the
  // launch is kept and this is recorded beside it.
  //
  // The wrapper is the one place that can say this. It runs on every
  // invocation of every harness, including a Declared one that fires no
  // hooks at all, so the announce covers the tiers the event channel
  // structurally cannot.
  //
  // And why the id is minted HERE rather than in the wrapper: a session
  // id is only worth anything once it is written down — `harness_session_id`
  // is what every future resume of this session reads — so a shell that
  // minted its own would still have to call in to report it. One call
  // does both. It is minted per LAUNCH, not per session: `VOLLI_SESSION`
  // is stamped once per PTY, and a harness that treats its session id as
  // single-use per workspace (cursor mkdirs a directory named after it)
  // fails outright on the second launch in one terminal.
  const sessionId = request.ctx.env.session;
  if (!sessionId) {
    return failure("CONTEXT_REQUIRED", "session harness requires VOLLI_SESSION context.");
  }
  const projection = await sessionEngine.getSession({ sessionId });
  const session = projection === null ? null : terminalSessionRecord(projection);
  if (!session) return failure("SESSION_NOT_FOUND", `No session matches ${sessionId}.`);
  // Ended is ended, the same rule `hook` applies and for the same reason:
  // `VOLLI_SESSION` is exported into the terminal's environment, so a tmux
  // server or a disowned daemon started inside a Volli session carries it
  // forever. Accepting an announce from one would rewrite the harness a
  // dead session resumes with, months later.
  if (session.endedAt !== null) {
    return failure("SESSION_ENDED", `Session ${shortSessionId(session.id)} has ended.`);
  }
  const slug = request.args["id"];
  if (typeof slug !== "string") {
    return failure("INVALID_REQUEST", "session harness requires a harness slug.");
  }
  // The same vocabulary check a fired hook passes — one definition of
  // "a harness Volli knows", not a second one that could drift from it.
  const announced = firingHarnessId(options.db, session, slug);
  if (!announced.ok) return announced.response;
  const harnessId = announced.harnessId;
  // The only honest place to count a launch. This call is made by the
  // wrapper Volli generated, one step before it execs, so it is proof
  // that our configuration was in the loop — which is exactly what has to
  // be true for the silence afterwards to mean anything. Counting at the
  // PTY spawn instead would also count `/opt/homebrew/bin/claude` typed by
  // hand, a launch that never saw our hooks, and manufacture a false
  // accusation out of a user's own shell habit.
  //
  // Ungated, unlike `active_harness_id` above: a relaunch of the same
  // harness is a new launch whose channel has proved nothing yet, and it
  // is the case the whole table exists to catch.
  recordHarnessLaunch(options.db, harnessId, now());
  // The WRITE is gated on a change: `active_harness_id` records which
  // harness is running, and re-storing the value already there is a
  // durable write bought for nothing.
  //
  // The BROADCAST is not, and that distinction is the point. This call is
  // proof that a launch just happened — the wrapper runs once per
  // invocation, out of the harness's own process — and the renderer's
  // grace window is anchored to it. Gating the broadcast on a changed
  // slug meant the second launch in one terminal (quit claude, run claude
  // again: the exact case the mint below exists for) was never announced,
  // so it inherited the first launch's `startedAt` and its already
  // `delivered` channel, and could never be judged silent. `changed`
  // stays ON the notice — the renderer still needs it to decide whether
  // to repoint the durable record's labels — but it stops being the gate.
  let changed = false;
  const nativeUpdate = await updateTerminalNative(
    terminalUpdateLocks,
    sessionEngine,
    session,
    (detail) => {
      changed = harnessId !== (detail.activeHarnessId ?? detail.harnessId);
      return detail.activeHarnessId === harnessId
        ? detail
        : { ...detail, activeHarnessId: harnessId };
    },
    now(),
  );
  if (nativeUpdate === null)
    return failure("SESSION_ENDED", `Session ${shortSessionId(session.id)} has ended.`);
  options.onSessionHarness?.({
    sessionId: session.id,
    projectId: session.projectId,
    ticketId: session.ticketId,
    harnessId,
    changed,
    at: now(),
  });
  // Only when the caller asked. The wrapper asks exactly when the adapter
  // it was rendered from takes an id on argv, and that is the only place
  // the answer is known — a registered manifest's adapter never reaches
  // main's own table, so main cannot re-derive it here. For a `reported`
  // or `none` harness a minted id would overwrite the resume seed the
  // harness's own events are about to write with one it never heard of.
  //
  // `randomUUID` directly, not the injectable `newId` seam: the FORMAT is
  // the contract, not an implementation detail a test may vary. Cursor
  // validates strict v4 (`4` in the third group, `[89ab]` in the fourth)
  // and refuses a v7.
  const minted = request.args["mint"] === true ? randomUUID() : null;
  if (minted !== null) {
    // Overwrites, always. The seed belongs to the launch that is starting
    // now; the previous one describes an agent this terminal has quit.
    const mintedUpdate = await updateTerminalNative(
      terminalUpdateLocks,
      sessionEngine,
      nativeUpdate,
      (detail) => ({ ...detail, harnessSessionId: minted }),
      now(),
    );
    if (mintedUpdate === null) {
      return failure("SESSION_ENDED", `Session ${shortSessionId(session.id)} has ended.`);
    }
  }
  return {
    v: 1,
    ok: true,
    data: {
      session: shortSessionId(session.id),
      harness: harnessId,
      changed,
      harnessSessionId: minted,
    },
  };
}

/** `volli hook` — one canonical harness event for the current session. */
export async function hookVerb(
  context: AgentCommandContext,
  request: AgentRequest,
): Promise<AgentResponse> {
  const { options, projects, sessionEngine, terminalUpdateLocks, watermarks, now } = context;
  // The involuntary channel (harness-events): a hook the wrapper
  // configured, not something the agent chose to run. `VOLLI_SESSION` is
  // both the addressing and the harness's own session id, so an event
  // resolves the session the same way `session.done` does.
  const sessionId = request.ctx.env.session;
  if (!sessionId) {
    return failure("CONTEXT_REQUIRED", "hook requires VOLLI_SESSION context.");
  }
  const projection = await sessionEngine.getSession({ sessionId });
  const session = projection === null ? null : terminalSessionRecord(projection);
  if (!session) return failure("SESSION_NOT_FOUND", `No session matches ${sessionId}.`);
  // A session row outlives its PTY, and `VOLLI_SESSION` outlives both: it
  // is exported into the session's environment, so anything that escapes
  // that environment carries it forever — a tmux server started inside a
  // Volli terminal, a disowned daemon, or simply a hook that fires as its
  // own shell is exiting. Without this guard such an event is accepted in
  // full: it rewrites the resume seed, records a verified delivery, fires
  // a native "needs you" notification, and the renderer registers a fresh
  // expectation for it — resurrecting a dead session in the sidebar.
  //
  // Ended is ended. The event is refused rather than swallowed, so a
  // harness that really is still reporting says so in its own exit code
  // instead of leaving Volli quietly wrong.
  if (session.endedAt !== null) {
    return failure("SESSION_ENDED", `Session ${shortSessionId(session.id)} has ended.`);
  }
  const event = request.args["event"];
  if (!isHarnessEvent(event)) {
    return failure(
      "INVALID_REQUEST",
      `Invalid harness event ${JSON.stringify(event)} (valid: ${HARNESS_EVENTS.join(", ")})`,
    );
  }
  const firing = firingHarnessId(options.db, session, request.args["harness"]);
  if (!firing.ok) return firing.response;
  const harnessSessionId = trimmedHarnessSessionId(request.args["harnessSessionId"]);
  if (harnessSessionId === undefined) {
    return failure("INVALID_REQUEST", "The harness session id is not usable.");
  }
  // THE ORDERING RULE, main's half. Each event arrives on its own
  // short-lived hook process over its own connection, so two that fire
  // close together race and `now()` stamps the winner of that race rather
  // than the agent's own sequence. `firedAt` is what the firing end could
  // prove about the order; `supersededHarnessEvent` is the single
  // definition of stale, shared verbatim with the renderer so the two ends
  // cannot drift into disagreeing about one session.
  //
  // What supersession withholds is STATE — anything a newer delivery has
  // already answered. What it never withholds is the PROOF that a delivery
  // happened: the ledger below, and the renderer's `delivered`. That
  // proof is order-free, a fact about what this harness can do rather than
  // a value a later fact replaces, and suppressing it would make Volli
  // forget a capability it had just watched being exercised.
  //
  // An absent or equal `firedAt` is never superseded — see
  // {@link HarnessEventOrder}. An older `volli` sends no stamp at all, and
  // such an event must land exactly as it did before, not vanish for
  // failing to prove its own age.
  const firedAt = harnessEventOrder(request.args["firedAt"]);
  const superseded = supersededHarnessEvent(watermarks.get(session.id) ?? null, firedAt);
  if (firedAt !== null && !superseded) rememberFiredAt(watermarks, session.id, firedAt);
  // A reported id is what replaces `session link` on the critical path.
  // Idempotent overwrite, exactly as `session.link` is — a harness that
  // rotates its id mid-session leaves the newest resume seed behind. Which
  // is precisely why a superseded one may not be written: newest by
  // arrival is not newest, and this row seeds every future resume.
  if (harnessSessionId !== null && !superseded) {
    await updateTerminalNative(
      terminalUpdateLocks,
      sessionEngine,
      session,
      (detail) => ({ ...detail, harnessSessionId }),
      now(),
    );
  }
  // The event arrived, so the harness can plainly deliver it: the ledger
  // learns that here, at the one place a delivery is observed, and before
  // anything is decided about this one. What comes back is what Volli now
  // knows about the capability — `absent` only for a harness it has no
  // record of at all.
  const status = recordHarnessDelivery(options.db, firing.harnessId, event, now());
  // The other half of the channel's two integers. Deliberately outside
  // every rule above it: a superseded event is still a delivery, and an
  // event nobody declared is still a delivery. This column answers "is
  // anything coming down this pipe", not "should this one be believed",
  // and withholding it would make a working channel look dead for the
  // sake of an event that merely arrived out of order.
  recordHarnessChannelEvent(options.db, firing.harnessId, now());
  // ONE event earns a notification: a human is blocking the agent's
  // progress. `subagent.completed` is telemetry — a subagent finishing is
  // not the parent finishing — and `permission.requested` is bound to the
  // same native signal as `input.needed` on every harness that has one, so
  // notifying on both would double every notification it earns.
  //
  // And only a verified capability interrupts a human. A declaration
  // cannot earn a notification (the plan doc's rule), which costs a real
  // delivery nothing — it verified itself one line above. `verified` is
  // about delivery, though, and says nothing about whether the harness can
  // report this at all, so the declaration is checked alongside it.
  //
  // The last condition is the disagreement rule. A notification is the
  // most expensive claim Volli makes — it interrupts a human and names an
  // agent — so it is made only where the two independent accounts agree:
  // the harness Volli launched this session with, and the hook that says
  // it fired. Anything in the session can invoke `volli hook` under a name
  // of its choosing, and a hand-typed second harness is indistinguishable
  // from a confused descendant. Everything cheaper follows the evidence
  // instead: the ledger and the fan-out are attributed to what fired.
  //
  // And it is withheld from a superseded delivery, which is the failure
  // that reads as noise rather than as a bug: an `input.needed` the agent
  // emitted before a `turn.started` that has already landed announces a
  // human is blocking something the agent moved past, and the user is
  // interrupted for a prompt they already answered. A notification cannot
  // be retracted, so it is the write that most needs to be sure.
  //
  // What the two accounts are compared AGAINST is the harness now
  // running, not the one the session launched with. Reading the launch
  // was the bug this rule was quietly causing: a user who quit opencode
  // and started claude got every one of claude's `input.needed` events
  // recorded in the ledger and none of them notified — silence in exactly
  // the case the feature exists for.
  if (
    event === "input.needed" &&
    status === "verified" &&
    declaresInputNeeded(firing.harnessId) &&
    firing.harnessId === effectiveHarnessId(session) &&
    !superseded
  ) {
    const ticket = session.ticketId ? getTicket(options.db, session.ticketId) : undefined;
    const ticketProject = ticket ? projects.find(({ id }) => id === ticket.projectId) : undefined;
    const subject =
      ticket && ticketProject
        ? displayTicketId(ticketProject.ticketPrefix, ticket.ticketNumber)
        : session.title;
    options.notify?.(
      `${subject} needs you`,
      `${harnessLabel(effectiveHarnessId(session))} is waiting on a human`,
    );
  }
  // A superseded event is still announced, carrying its own `firedAt`, and
  // the renderer applies the same rule to it independently. Filtering here
  // instead would make the renderer's correctness depend on this map being
  // intact — and it is evicted at a cap and empty after a relaunch, while
  // the renderer's watermark lives with the session it describes. Two
  // places apply one rule; neither is the other's guard.
  options.onHarnessEvent?.({
    sessionId: session.id,
    projectId: session.projectId,
    ticketId: session.ticketId,
    harnessId: firing.harnessId,
    event,
    harnessSessionId,
    at: now(),
    firedAt,
  });
  // The firing harness is echoed back so a caller (and a `doctor` reading
  // a transcript) can see which one Volli credited, rather than having to
  // infer it from the session. `superseded` rides the same seam, and is
  // the only trace a rejected delivery leaves anywhere: the symptom of
  // this rule misfiring is a session that sits showing a wait the user
  // already answered, and nothing else in the app would ever explain it.
  // Nothing consumes the field yet — `volli hook` discards its response by
  // design — so it is legible to a socket transcript and to whatever
  // diagnostic next needs it, and costs nothing until then.
  return {
    v: 1,
    ok: true,
    data: {
      session: shortSessionId(session.id),
      harness: firing.harnessId,
      event,
      harnessSessionId,
      superseded,
    },
  };
}
