// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/cursor-tall.scene.json";
import recipe1 from "./scenes/cursor-wide.scene.json";
export const sceneModules = {
  "src/flute/scenes/cursor-tall.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/cursor-tall.tsx": () => import("./scenes/cursor-tall"),
  "src/flute/scenes/cursor-wide.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/cursor-wide.tsx": () => import("./scenes/cursor-wide"),
};
