// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/armed-tall.scene.json";
import recipe1 from "./scenes/armed-wide.scene.json";
import recipe2 from "./scenes/cursor-tall.scene.json";
import recipe3 from "./scenes/cursor-wide.scene.json";
import recipe4 from "./scenes/end-tall.scene.json";
import recipe5 from "./scenes/end-wide.scene.json";
import recipe6 from "./scenes/hook-tall.scene.json";
import recipe7 from "./scenes/hook-wide.scene.json";
import recipe8 from "./scenes/island-tall.scene.json";
import recipe9 from "./scenes/island-wide.scene.json";
import recipe10 from "./scenes/limits-tall.scene.json";
import recipe11 from "./scenes/limits-wide.scene.json";
import recipe12 from "./scenes/models-tall.scene.json";
import recipe13 from "./scenes/models-wide.scene.json";
import recipe14 from "./scenes/palette-tall.scene.json";
import recipe15 from "./scenes/palette-wide.scene.json";
import recipe16 from "./scenes/picker-tall.scene.json";
import recipe17 from "./scenes/picker-wide.scene.json";
import recipe18 from "./scenes/rail-tall.scene.json";
import recipe19 from "./scenes/rail-wide.scene.json";
import recipe20 from "./scenes/scale-tall.scene.json";
import recipe21 from "./scenes/scale-wide.scene.json";
import recipe22 from "./scenes/split-tall.scene.json";
import recipe23 from "./scenes/split-wide.scene.json";
export const sceneModules = {
  "src/flute/scenes/armed-tall.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/armed-tall.tsx": () => import("./scenes/armed-tall"),
  "src/flute/scenes/armed-wide.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/armed-wide.tsx": () => import("./scenes/armed-wide"),
  "src/flute/scenes/cursor-tall.scene.json": async () => ({default:recipe2}),
  "src/flute/scenes/cursor-tall.tsx": () => import("./scenes/cursor-tall"),
  "src/flute/scenes/cursor-wide.scene.json": async () => ({default:recipe3}),
  "src/flute/scenes/cursor-wide.tsx": () => import("./scenes/cursor-wide"),
  "src/flute/scenes/end-tall.scene.json": async () => ({default:recipe4}),
  "src/flute/scenes/end-tall.tsx": () => import("./scenes/end-tall"),
  "src/flute/scenes/end-wide.scene.json": async () => ({default:recipe5}),
  "src/flute/scenes/end-wide.tsx": () => import("./scenes/end-wide"),
  "src/flute/scenes/hook-tall.scene.json": async () => ({default:recipe6}),
  "src/flute/scenes/hook-tall.tsx": () => import("./scenes/hook-tall"),
  "src/flute/scenes/hook-wide.scene.json": async () => ({default:recipe7}),
  "src/flute/scenes/hook-wide.tsx": () => import("./scenes/hook-wide"),
  "src/flute/scenes/island-tall.scene.json": async () => ({default:recipe8}),
  "src/flute/scenes/island-tall.tsx": () => import("./scenes/island-tall"),
  "src/flute/scenes/island-wide.scene.json": async () => ({default:recipe9}),
  "src/flute/scenes/island-wide.tsx": () => import("./scenes/island-wide"),
  "src/flute/scenes/limits-tall.scene.json": async () => ({default:recipe10}),
  "src/flute/scenes/limits-tall.tsx": () => import("./scenes/limits-tall"),
  "src/flute/scenes/limits-wide.scene.json": async () => ({default:recipe11}),
  "src/flute/scenes/limits-wide.tsx": () => import("./scenes/limits-wide"),
  "src/flute/scenes/models-tall.scene.json": async () => ({default:recipe12}),
  "src/flute/scenes/models-tall.tsx": () => import("./scenes/models-tall"),
  "src/flute/scenes/models-wide.scene.json": async () => ({default:recipe13}),
  "src/flute/scenes/models-wide.tsx": () => import("./scenes/models-wide"),
  "src/flute/scenes/palette-tall.scene.json": async () => ({default:recipe14}),
  "src/flute/scenes/palette-tall.tsx": () => import("./scenes/palette-tall"),
  "src/flute/scenes/palette-wide.scene.json": async () => ({default:recipe15}),
  "src/flute/scenes/palette-wide.tsx": () => import("./scenes/palette-wide"),
  "src/flute/scenes/picker-tall.scene.json": async () => ({default:recipe16}),
  "src/flute/scenes/picker-tall.tsx": () => import("./scenes/picker-tall"),
  "src/flute/scenes/picker-wide.scene.json": async () => ({default:recipe17}),
  "src/flute/scenes/picker-wide.tsx": () => import("./scenes/picker-wide"),
  "src/flute/scenes/rail-tall.scene.json": async () => ({default:recipe18}),
  "src/flute/scenes/rail-tall.tsx": () => import("./scenes/rail-tall"),
  "src/flute/scenes/rail-wide.scene.json": async () => ({default:recipe19}),
  "src/flute/scenes/rail-wide.tsx": () => import("./scenes/rail-wide"),
  "src/flute/scenes/scale-tall.scene.json": async () => ({default:recipe20}),
  "src/flute/scenes/scale-tall.tsx": () => import("./scenes/scale-tall"),
  "src/flute/scenes/scale-wide.scene.json": async () => ({default:recipe21}),
  "src/flute/scenes/scale-wide.tsx": () => import("./scenes/scale-wide"),
  "src/flute/scenes/split-tall.scene.json": async () => ({default:recipe22}),
  "src/flute/scenes/split-tall.tsx": () => import("./scenes/split-tall"),
  "src/flute/scenes/split-wide.scene.json": async () => ({default:recipe23}),
  "src/flute/scenes/split-wide.tsx": () => import("./scenes/split-wide"),
};
