// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/cursor-tall.scene.json";
import recipe1 from "./scenes/cursor-wide.scene.json";
import recipe2 from "./scenes/end-tall.scene.json";
import recipe3 from "./scenes/end-wide.scene.json";
import recipe4 from "./scenes/hook-tall.scene.json";
import recipe5 from "./scenes/hook-wide.scene.json";
import recipe6 from "./scenes/limits-tall.scene.json";
import recipe7 from "./scenes/limits-wide.scene.json";
import recipe8 from "./scenes/models-tall.scene.json";
import recipe9 from "./scenes/models-wide.scene.json";
import recipe10 from "./scenes/split-tall.scene.json";
import recipe11 from "./scenes/split-wide.scene.json";
export const sceneModules = {
  "src/flute/scenes/cursor-tall.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/cursor-tall.tsx": () => import("./scenes/cursor-tall"),
  "src/flute/scenes/cursor-wide.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/cursor-wide.tsx": () => import("./scenes/cursor-wide"),
  "src/flute/scenes/end-tall.scene.json": async () => ({default:recipe2}),
  "src/flute/scenes/end-tall.tsx": () => import("./scenes/end-tall"),
  "src/flute/scenes/end-wide.scene.json": async () => ({default:recipe3}),
  "src/flute/scenes/end-wide.tsx": () => import("./scenes/end-wide"),
  "src/flute/scenes/hook-tall.scene.json": async () => ({default:recipe4}),
  "src/flute/scenes/hook-tall.tsx": () => import("./scenes/hook-tall"),
  "src/flute/scenes/hook-wide.scene.json": async () => ({default:recipe5}),
  "src/flute/scenes/hook-wide.tsx": () => import("./scenes/hook-wide"),
  "src/flute/scenes/limits-tall.scene.json": async () => ({default:recipe6}),
  "src/flute/scenes/limits-tall.tsx": () => import("./scenes/limits-tall"),
  "src/flute/scenes/limits-wide.scene.json": async () => ({default:recipe7}),
  "src/flute/scenes/limits-wide.tsx": () => import("./scenes/limits-wide"),
  "src/flute/scenes/models-tall.scene.json": async () => ({default:recipe8}),
  "src/flute/scenes/models-tall.tsx": () => import("./scenes/models-tall"),
  "src/flute/scenes/models-wide.scene.json": async () => ({default:recipe9}),
  "src/flute/scenes/models-wide.tsx": () => import("./scenes/models-wide"),
  "src/flute/scenes/split-tall.scene.json": async () => ({default:recipe10}),
  "src/flute/scenes/split-tall.tsx": () => import("./scenes/split-tall"),
  "src/flute/scenes/split-wide.scene.json": async () => ({default:recipe11}),
  "src/flute/scenes/split-wide.tsx": () => import("./scenes/split-wide"),
};
