#!/usr/bin/env node
/**
 * The release film's ticket fixture (VC-464): every Volli ticket whose work
 * landed between v0.1.2 and v0.2.0, with a title that is already public.
 *
 *   node scripts/film/tickets.mjs [--board /path/to/volli-ticket-list.json]
 *
 * Which tickets: every distinct `VC-<n>` in a commit SUBJECT in
 * `git log v0.1.2..v0.2.0` (177), less any the board does not have in Done
 * (VC-30 is still Doing, VC-266 is in Backlog) — the 175 the film states.
 *
 * Which title: the film may only show what is already public, and commit
 * history is public. So a title comes from, in order:
 *   1. the board title, when the ticket's merged branch slug
 *      (`volli/VC-<n>-<slug>` in a merge commit) is that title slugified — the
 *      branch name already published it — cut to the words the slug covers;
 *   2. the pull request title a merge commit carries for that branch;
 *   3. the first commit subject naming the ticket, conventional prefix and id
 *      stripped.
 * `--board` is the JSON of `volli ticket list --json` (read-only, optional);
 * without it, only 2 and 3 apply.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const desktop = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const RANGE = "v0.1.2..v0.2.0";
const git = (...args) => execFileSync("git", args, { cwd: desktop, encoding: "utf8" });

const boardArg = process.argv.indexOf("--board");
const board =
  boardArg === -1
    ? new Map()
    : new Map(
        JSON.parse(readFileSync(process.argv[boardArg + 1], "utf8")).tickets.map((t) => [t.id, t]),
      );

const subjects = git("log", "--reverse", "--format=%s", RANGE).split("\n").filter(Boolean);
const ids = [];
for (const subject of subjects) {
  for (const match of subject.matchAll(/VC-(\d+)/g)) {
    if (!ids.includes(Number(match[1]))) ids.push(Number(match[1]));
  }
}

// Merge commits: branch slug + PR title (the body's first line).
const merges = new Map();
for (const block of git("log", "--merges", "--format=%s%x1f%b%x1e", RANGE).split("\x1e")) {
  const [subject = "", body = ""] = block.trim().split("\x1f");
  const match = /volli\/VC-(\d+)-([a-z0-9-]+)/.exec(subject);
  if (match === null) continue;
  const number = Number(match[1]);
  if (!merges.has(number)) merges.set(number, { slug: match[2], pr: body.trim().split("\n")[0] });
}

const slugify = (text) =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

/** The longest word-prefix of `title` whose slug the published slug covers. */
function coveredPrefix(title, slug) {
  const words = title.split(/\s+/);
  let best = "";
  for (let n = 1; n <= words.length; n += 1) {
    const prefix = words.slice(0, n).join(" ");
    const s = slugify(prefix);
    if (slug.startsWith(s)) best = prefix;
    else break;
  }
  return best;
}

const strip = (subject, number) =>
  subject
    .replace(/^Merge\s+/, "")
    .replace(/\s*\(review-passed\)\s*$/, "")
    .replace(/\s*\(#\d+\)\s*$/, "")
    .replace(/^VC-\d+:\s*/, "")
    .replace(/^[a-z]+(\([^)]*\))?!?:\s*/i, "")
    .replace(new RegExp(`\\s*\\(?VC-${number}\\)?:?\\s*`, "g"), " ")
    .trim()
    .replace(/^./, (c) => c.toUpperCase());

/**
 * Public text, shortened where the full subject states something the film must
 * not claim: VC-385's percentage was measured on a dirty tree.
 */
const OVERRIDES = new Map([[385, "Cut ticket workspace switching"]]);

const shipped = board.size === 0 ? ids : ids.filter((n) => board.get(`VC-${n}`)?.status === "done");
if (board.size > 0) {
  const dropped = ids.filter((n) => !shipped.includes(n));
  console.log(`not Done on the board, left out: ${dropped.map((n) => `VC-${n}`).join(", ")}`);
}

const rows = shipped.map((number) => {
  const merge = merges.get(number);
  const boardTicket = board.get(`VC-${number}`);
  let title = null;
  let source = null;
  if (merge && boardTicket) {
    // The published slug is the title's own opening words: the owner's
    // title is the one the branch was cut from, so the whole title is used.
    const covered = coveredPrefix(boardTicket.title, merge.slug);
    if (covered.split(/\s+/).length >= 3) {
      title = boardTicket.title;
      source = "branch";
    }
  }
  if (title === null && merge?.pr) {
    title = strip(merge.pr, number);
    source = "pr";
  }
  if (title === null) {
    const subject = subjects.find((s) => new RegExp(`VC-${number}\\b`).test(s));
    title = strip(subject, number);
    source = "commit";
  }
  if (OVERRIDES.has(number)) {
    title = OVERRIDES.get(number);
    source = "override";
  }
  title = title.replace(/[\s,:;–—(-]+$/, "");
  return { number, title, source };
});

const out = join(desktop, "src", "flute", "kit", "release-tickets.ts");
writeFileSync(
  out,
  `/**
 * GENERATED by scripts/film/tickets.mjs — do not edit.
 *
 * Every Done ticket whose number appears in a commit subject in ${RANGE}
 * (${rows.length} tickets), titled only with text commit history already published
 * (see the script for the order of sources).
 */
export const RELEASE_RANGE = ${JSON.stringify(RANGE)};

export const RELEASE_TICKETS: readonly { number: number; title: string }[] = ${JSON.stringify(
    rows.map(({ number, title }) => ({ number, title })),
    null,
    2,
  )};
`,
);
console.log(`wrote ${out}: ${rows.length} tickets`);
const bySource = rows.reduce((acc, r) => ((acc[r.source] = (acc[r.source] ?? 0) + 1), acc), {});
console.log(bySource);
